# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application Deployment

on:          
  workflow_call:
    secrets:
      TEST_ROLE:
        required: true
    inputs:
      environment:
        required: true
        default: 'dev'
        type: string

permissions:
  contents: read

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Test with pytest
        run: |
          echo "Execute a deployment."
          echo ${{ inputs.environment }}
