# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application Main Flow

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qas
          - prd
        
  pull_request:
    branches: [ "main" ]
    types: ["opened", "synchronize", "closed"]

permissions:
  contents: read

jobs:
  call-unit-test:
    uses: ./.github/workflows/python-app-unittest.yml
  check-deployment:
    runs-on: ubuntu-latest
    needs:
      - call-unit-test
    if: github.event.pull_request.merged == true
    outputs:
      output_dev_deployment: ${{ steps.dev_deployment.outputs.dev }}
    steps:
      - id: dev_deployment
        run: echo "dev=yes" >> "$GITHUB_OUTPUT"
  call-deployment:
    needs: 
      - call-unit-test
      - check-deployment
    if: ${{needs.check-deployment.outputs.output_dev_deployment}} == 'yes' || github.event_name == 'workflow_dispatch' && github.event.inputs.environment != ''
    uses: ./.github/workflows/python-app-deployment.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit
